language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ercankurtoglu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ercankurtoglu/react-test npm test

after_success:
  - docker build -t ercankurtoglu/multi-client ./client
  - docker build -t ercankurtoglu/multi-nginx ./nginx
  - docker build -t ercankurtoglu/multi-server ./server
  - docker build -t ercankurtoglu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ercankurtoglu/multi-client
  - docker push ercankurtoglu/multi-nginx
  - docker push ercankurtoglu/multi-server
  - docker push ercankurtoglu/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-1-588738596885
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY